#!/usr/bin/env bash
set -euo pipefail

# Set environment
export OUTDIR="$RGH_PROJECTIONS_VOL_DIR/jobs/rgh_simulation/mc_rgh"

# Merge submit helper for outputs produced by jobs in this directory
# Groups .hipo files into batches of $RGH_NMERGE_FILES and submits one sbatch job per batch

cd "${RGH_PROJECTIONS_HOME:-.}/jobs/rgh_simulation/mc_rgh" || exit 1

# Required environment variables (should be set by bin/env.sh or bin/env.csh)
: "${RGH_HIPO_UTILS_COMMAND:?Please set RGH_HIPO_UTILS_COMMAND in your environment ($RGH_PROJECTIONS_HOME/env.txt)}"
: "${RGH_NMERGE_FILES:?Please set RGH_NMERGE_FILES in your environment ($RGH_PROJECTIONS_HOME/env.txt)}"

NMERGE_FILES=${RGH_NMERGE_FILES}

# File to collect all sbatch submit commands so the user can run them separately
submit_all="submit_all_merge_jobs.sh"
# Initialize/overwrite the submit-all wrapper
cat > "$submit_all" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
# Wrapper to submit all merge SBATCH jobs generated by this script.
# Run: ./submit_all_merge_jobs.sh
EOF
chmod +x "$submit_all"

# Collect .hipo files produced by the jobs. Exclude files that look like already-merged outputs
shopt -s nullglob
hipo_files=( $OUTDIR/dst/*.hipo )
filtered=()
for f in "${hipo_files[@]}"; do
    if [[ "$f" == *merged* || "$f" == *_merged* ]]; then
        continue
    fi
    filtered+=("$f")
done

total=${#filtered[@]}
if [ "$total" -eq 0 ]; then
    echo "No .hipo files to merge in $PWD"
    exit 0
fi

echo "Found $total .hipo files to merge. Splitting into positive/negative target-polarization groups (per jobs/c12analysis/mc_rgh/job.sh) and batching into $NMERGE_FILES per merge..."

# Prepare merged output dir
mkdir -p "$OUTDIR/merged"

# Split into pos/neg groups using the same rule as job.sh
pos_group=()
neg_group=()
if [ -z "${CLASDIS_GEN_PM:-}" ] || [ "${CLASDIS_GEN_PM}" -eq 0 ] 2>/dev/null; then
    # CLASDIS_GEN_PM unset or zero -> all files treated as positive-target spin
    pos_group=( "${filtered[@]}" )
else
    for f in "${filtered[@]}"; do
        name=$(basename "$f")
        if echo "$name" | grep -q "${CLASDIS_PREFIX}-${CLASDIS_POL}_"; then
            # matches pattern -> goes into negative-target group (TSPIN_SIGN=-1)
            neg_group+=("$f")
        else
            pos_group+=("$f")
        fi
    done
fi

# Function to write batches for a named array (portable, avoids nameref)
write_group_batches() {
    local array_name="$1"  # name of array variable holding file paths
    local label="$2"       # label to use in output filenames (pos/neg)
    local files
    # copy named array into local 'files' array
    eval "files=( \"\${${array_name}[@]}\" )"
    local total_g=${#files[@]}
    if [ "$total_g" -eq 0 ]; then
        echo "No files for group: $label"
        return
    fi

    local idx=0
    local grp_id=0
    while [ $idx -lt $total_g ]; do
        local start=$idx
        local end=$(( idx + NMERGE_FILES - 1 ))
        if [ $end -ge $(( total_g - 1 )) ]; then
            end=$(( total_g - 1 ))
        fi
        local count=$(( end - start + 1 ))
        grp_id=$(( grp_id + 1 ))

        local inputs=( "${files[@]:$start:$count}" )
        local outfile="$OUTDIR/merged/merged_${label}_${grp_id}.hipo"
        local mergescript="merge_${label}_${grp_id}.sh"
        local submitscript="submit_merge_${label}_${grp_id}.sh"

        cat > "$mergescript" <<EOF
#!/usr/bin/env bash
set -euo pipefail
cd "${RGH_PROJECTIONS_HOME:-.}/jobs/rgh_simulation/mc_rgh"
${RGH_HIPO_UTILS_COMMAND} -merge -o "$outfile" ${inputs[*]}
EOF
        chmod +x "$mergescript"

        cat > "$submitscript" <<EOF
#!/usr/bin/env bash
#SBATCH --job-name=merge_${label}_${grp_id}
#SBATCH --output=$RGH_PROJECTIONS_FARM_OUT/%x-%j-%N.out
#SBATCH --error=$RGH_PROJECTIONS_FARM_OUT/%x-%j-%N.err
#SBATCH --partition=$RGH_HPC_PARTITION
#SBATCH --account=$RGH_HPC_ACCOUNT
#SBATCH --mem-per-cpu=4000
#SBATCH --time=24:00:00
bash "$(pwd)/$mergescript"
EOF

        echo "Adding submit entry for $label group files ${start}..${end} -> $outfile"
        echo "sbatch \"$(pwd)/$submitscript\"" >> "$submit_all"

        idx=$(( end + 1 ))
    done

    echo "Wrote $grp_id merge jobs for group: $label"
}

# Write batches for positive and negative groups separately
write_group_batches pos_group pos
write_group_batches neg_group neg

echo "Wrote merge job scripts and a submit-all wrapper: $submit_all"
echo "To submit the merge jobs, run: ./$submit_all"
