#!/usr/bin/env bash
set -euo pipefail

# Set environment
export OUTDIR="$RGH_PROJECTIONS_VOL_DIR/jobs/rgh_simulation/mc_rgh"

# Merge submit helper for outputs produced by jobs in this directory
# Groups .hipo files into batches of $RGH_NMERGE_FILES and submits one sbatch job per batch

cd "${RGH_PROJECTIONS_HOME:-.}/jobs/rgh_simulation/mc_rgh" || exit 1

# Required environment variables (should be set by bin/env.sh or bin/env.csh)
: "${RGH_HIPO_UTILS_COMMAND:?Please set RGH_HIPO_UTILS_COMMAND in your environment ($RGH_PROJECTIONS_HOME/env.txt)}"
: "${RGH_NMERGE_FILES:?Please set RGH_NMERGE_FILES in your environment ($RGH_PROJECTIONS_HOME/env.txt)}"

NMERGE_FILES=${RGH_NMERGE_FILES}

# File to collect all sbatch submit commands so the user can run them separately
submit_all="submit_all_merge_jobs.sh"
# Initialize/overwrite the submit-all wrapper
cat > "$submit_all" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
# Wrapper to submit all merge SBATCH jobs generated by this script.
# Run: ./submit_all_merge_jobs.sh
EOF
chmod +x "$submit_all"

# Collect .hipo files produced by the jobs. Exclude files that look like already-merged outputs
shopt -s nullglob
hipo_files=( $OUTDIR/dst/*.hipo )
filtered=()
for f in "${hipo_files[@]}"; do
    if [[ "$f" == *merged* || "$f" == *_merged* ]]; then
        continue
    fi
    filtered+=("$f")
done

total=${#filtered[@]}
if [ "$total" -eq 0 ]; then
    echo "No .hipo files to merge in $PWD"
    exit 0
fi

echo "Found $total .hipo files to merge. Grouping into batches of $NMERGE_FILES..."

grp=0
i=0
while [ $i -lt $total ]; do
    start=$i
    end=$(( i + NMERGE_FILES - 1 ))
    if [ $end -ge $(( total - 1 )) ]; then
        end=$(( total - 1 ))
    fi
    count=$(( end - start + 1 ))
    grp=$(( grp + 1 ))

    # Prepare input list for this group
    inputs=( "${filtered[@]:$start:$count}" )
    outfile="$OUTDIR/merged/merged_${grp}.hipo"
    mergescript="merge_job_${grp}.sh"
    submitscript="submit_merge_${grp}.sh"

    # Write the actual merge command script
    cat > "$mergescript" <<EOF
#!/usr/bin/env bash
set -euo pipefail
cd "${RGH_PROJECTIONS_HOME:-.}/jobs/rgh_simulation/mc_rgh"
\$RGH_HIPO_UTILS_COMMAND -merge -o "$outfile" ${inputs[*]}
EOF
    chmod +x "$mergescript"

    # Write a minimal sbatch submit script for the merge job
    cat > "$submitscript" <<EOF
#!/usr/bin/env bash
#SBATCH --job-name=mc_rgh_merge
#SBATCH --output=$RGH_PROJECTIONS_FARM_OUT/%x-%j-%N.out
#SBATCH --error=$RGH_PROJECTIONS_FARM_OUT/%x-%j-%N.err
#SBATCH --partition=$RGH_HPC_PARTITION
#SBATCH --account=$RGH_HPC_ACCOUNT
#SBATCH --mem-per-cpu=4000
#SBATCH --time=24:00:00
bash "$(pwd)/$mergescript"
EOF

    # Add the sbatch invocation to the submit-all wrapper (do not submit here)
    echo "Adding submit entry for merge job files ${start}..${end} -> $outfile"
    echo "sbatch \"$(pwd)/$submitscript\"" >> "$submit_all"

    i=$(( end + 1 ))
done

echo "Wrote $grp merge job scripts and a submit-all wrapper: $submit_all"
echo "To submit the merge jobs, run: ./$submit_all"
